### ISSUE TITLE
CopyCFrame is not a valid member of the Enum. & Client bind to close error

### ISSUE THREAD

**Issue by InnLumin** [LadyCelastia/HitboxRemaster#1]
Hello when using the module it spams an error that "CopyCFrame" is not a enum.

![RobloxStudioBeta_FR10MN9llR](https://github.com/LadyCelastia/HitboxRemaster/assets/94868961/fb57d4f1-2ff8-45b0-9ea2-bcef3e8f5533)

This was from using the example code.

![RobloxStudioBeta_DEyTWL7ggx](https://github.com/LadyCelastia/HitboxRemaster/assets/94868961/02bcb674-fd55-495f-8d01-56323b2d61c6)

When using the same exact code but on the client there's a bind to close error

![image](https://github.com/LadyCelastia/HitboxRemaster/assets/94868961/deb1bf3c-944e-41a6-90d4-292884e98818)

My formatter has changed the lines of the file but this can be tested with the normal file.

**Comment by LadyCelastia** [comment]
Looking into it, thanks for the report

**Comment by LadyCelastia** [comment]
Root cause identified and fix applied, should be fixed now.

**Comment by InnLumin** [comment]
Hello,
The issues seems to be fix but, there is a new bug.
 
![image](https://github.com/LadyCelastia/HitboxRemaster/assets/94868961/550c035b-4378-489c-8b75-32968bac211b)

**Comment by LadyCelastia** [comment]
Will fix this as soon as possible when I get on tomorrow and push a fix and test it, I'll reply again when a fix is ready and tested.

**Comment by LadyCelastia** [comment]
This is most likely a bug on your end, as line 697 executes the function you've embedded into your ScriptConnection. I'll try to improve the stack tracer so it'll show the error in your embedded function instead of the module for easier bug identification on your end.

**Comment by LadyCelastia** [comment]
Attempted to improve the stack tracer by parsing a vararg emulator into a pcall. Merged

**Comment by InnLumin** [comment]
The error above, the stack trace actually completely removes the error in the output but it is still erroring as the rest of the code doesn't run. The problem itself is actually:
![image](https://github.com/LadyCelastia/HitboxRemaster/assets/94868961/d16aac6f-f758-4abb-9dd0-12703bb986a9)

You are comparing a CFrame with a number "CFrame > 0" not to mention you are calling :inverse() instead of :Inverse() I had fixed it with this code but the backstab doesn't come up as true. Also :IsBackStab() warns of no humanoidrootpart when giving a proper character, mainly it's just how the conditional was made. This is a picture I did that fixed it although, it still doesn't come up true when actually backstabing though:
![image](https://github.com/LadyCelastia/HitboxRemaster/assets/94868961/448a900f-6040-4cd9-81a1-43f7a39e2929)

[HitboxRemasterError.zip](https://github.com/LadyCelastia/HitboxRemaster/files/12853808/HitboxRemasterError.zip)

**Comment by LadyCelastia** [comment]
Backstab just got fixed in the latest update, it should work perfectly with your tools now. (You still need to add in the Hitbox:AddIgnore() though)

**Comment by InnLumin** [comment]
I will be testing the code more thoroughly but the error already is that if you don't pass in margin it errors. The stack trace change you mention earlier seems to just completely omit any output code.

**Comment by LadyCelastia** [comment]
Both fixed, thanks.

**Comment by InnLumin** [comment]
😅 Seems to have broken the entire module

**Comment by LadyCelastia** [comment]
Debugging be like...

I'm reverting the entire vararg emulator on stack tracer, it's too big brain for me to make it work.

**Comment by InnLumin** [comment]
Haha, might be worth breaking the code into separate modules. Otherwise everything seems to be working so I'll close the threads and keep testing things on my end. Thanks!
