### ISSUE TITLE
Enhancement for CopyCFrame

### ISSUE THREAD

**Issue by BifidoKephir** [LadyCelastia/HitboxRemaster#3]
Make CopyCFrame copying more flexible by allowing users to choose which properties to duplicate. This feature would add customization options for a more efficient workflow.

**Comment by LadyCelastia** [comment]
Seems like a good idea. I can see how overriding several properties simultaneously would cause issues. Should be able to push out an update today or tomorrow. I'll try to make the new CopyCFrame backward compatible.

**Comment by LadyCelastia** [comment]
Feature completed and added. Using it the old way would work just fine with this new system, but there's a new property that allows you to select what to copy over.
https://ladycelastia.github.io/HitboxRemaster/api/Hitbox/
Hitbox.new and Hitbox.CopyCFrameProperties have information about this new property. If you have any suggestion or issue, feel free to tell me.

**Comment by LadyCelastia** [comment]
If there's nothing else, allow me to close the issue. Thanks!
